### ISSUE TITLE
New Moon - SSE

### ISSUE THREAD

**Issue by Reino17** [roytam1/palemoon26#1]
Hello roytam1,

Sorry for contacting you this way, but I can't login at MSFN anymore and the admins there, despite having sent them messages about it multiple times, just won't help me...

I'm running your New Moon builds on a AMD Athlon XP 3200+. This cpu has no SSE2 capabilities, but it does have SSE.
Only the ia32 builds seem to work here, because the "normal" builds crash immediately. I take it these contain some SSE2 code.
Would it be possible for you to release some SSE builds?

**Comment by roytam1** [comment]
SSE-enabled build(s) are possible for PM27, but not PM28/BK52.
I can create a build later.

**Comment by roytam1** [comment]
you may try if https://o.rthost.cf/palemoon/palemoon-27.9.1a1.win32-git-20180526-23668d3d5-xpmod-sse.7z works

**Comment by Reino17** [comment]
It does! Thanks a lot. Much appreciated.
Too bad PM28 can't be built this way.
